import React from 'react'
import Techpost from './Techpost'

const Updates = () => {
  return (
    <>
      <Techpost p1="Redmi 13 5G India launch set for July 9, Amazon reveals design and key specs ahead of event" p2="The Redmi 13 5G will launch in India soon. Amazon has published a page dedicated to this Redmi phone, revealing the Redmi 13's key specs, design, launch date and other details. It is expected to be priced under Rs 15,000. Keep reading to know more." p3="https://akm-img-a-in.tosshub.com/indiatoday/images/story/202406/redmi-13-5g-210648626-16x9.jpg?VersionId=I6kxwPgMuyBlV9iqWC10OrOZApVk2WdH" />
      <Techpost p1="Realme GT 6T review: The mid-range powerhouse" p2="Realme GT 6T is a mid-range smartphone that combines high-end features with a sleek design, offering excellent performance and a stunning display" p3="https://akm-img-a-in.tosshub.com/indiatoday/images/story/202406/realme-gt-6t-215733770-16x9_0.png?VersionId=JL3vLGr02JzLagP58rHaj9RzgLDO44Sa&size=690:388" />
      <Techpost p1="Next-gen ChatGPT will have PhD level intelligence: OpenAI CTO Mira Murati" p2="OpenAI CTO Mira Murati says the next generation ChatGPT will have PhD-level intelligence, and in a lot of tasks it will seem smarter than humans." p3="https://akm-img-a-in.tosshub.com/indiatoday/images/story/202406/mira-murati-08493013-1x1.png?VersionId=ChbXiBJ3nZrTszwyuvUs.IxMziBkHuzi&size=115:115" />
      <Techpost p1="iQOO 13 rumours surface online: Bigger battery, camera upgrades and all we can expect" p2="The iQOO 13 is expected to launch in November this year. Various leaks about the phone's chipset, camera, and design have surfaced online." p3="https://akm-img-a-in.tosshub.com/indiatoday/images/story/202406/iqoo-12-5g-210554945-1x1.jpg?VersionId=zwODDVfiFlimFuqYl7KM8PAADQoINL_r&size=115:115" />
      <Techpost p1="OnePlus Nord 3 selling under Rs 20,000 during Amazon Monsoon Mobile Mania sale" p2="The OnePlus Nord 3 is selling under Rs 20,000 during Amazon Monsoon Mobile Mania sale, which is quite surprising because the device was announced at Rs 33,999. It will likely give" p3="https://akm-img-a-in.tosshub.com/indiatoday/images/story/202406/oneplus-nord-3-051141191-16x9.jpg?VersionId=h2EWYI8TgTMMsClEUhpgauoQEyGw2PmP&size=690:388" />
      <Techpost p1="YouTube to ask Apple users for location sharing to show personalized ads" p2="YouTube is introducing a new prompt for Apple device users to seek consent to track their activity to deliver personalised ads. This change" p3="https://akm-img-a-in.tosshub.com/indiatoday/images/story/202406/youtube-165822594-1x1.jpg?VersionId=J7mF4UrxqDusM006TB5paAunRhuClBmQ&size=115:115" />
      <Techpost p1="iPhone 16 launching soon with big upgrades: bigger display, better camera and everything else expected" p2="Apple is set to unveil the iPhone 16 series in its upcoming fall event, bringing significant upgrades in display, camera, and performance." p3="https://akm-img-a-in.tosshub.com/indiatoday/images/story/202406/apple-unveils-record-110-billion-buyback-as-results-beat-low-expectations-033425382-16x9.jpg?VersionId=YeYCw_r6uV_qydc2e3Vxdhby1Q8hqIG6&size=690:388" />
      <Techpost p1="YouTube might cancel Premium subscriptions purchased through VPN, all details" p2="YouTube is reportedly taking action against users who use VPNs to buy cheaper Premium subscriptions from other countries. The platform might" p3="https://akm-img-a-in.tosshub.com/indiatoday/images/story/202406/youtube-181754736-1x1_0.png?VersionId=hqweYA4Kp4G.Wh9OBWb9KmxWakW3LRAZ&size=115:115" />
      <Techpost p1="OnePlus Nord CE 4 Lite India launch in 3 days: Expected price and specs" p2="YouTube is reportedly taking action against users who use VPNs to buy cheaper Premium subscriptions from other countries. The platform might" p3="https://akm-img-a-in.tosshub.com/indiatoday/images/story/202406/oneplus-nord-ce-4-lite-5g-19504732-1x1.jpg?VersionId=6707cPT3HmvxkQVI1ph6bmQ8s2MTGrvL&size=115:115" />
    </>
  )
}

export default Updates